### ISSUE TITLE
No localization with Livox Lidar

### ISSUE THREAD

**Issue by WeilongXia** [vectr-ucla/direct_lidar_inertial_odometry#5]
Thanks a lot for opening source such a great work, but when I run the code, I found that the odometry output pose has always been the origin and has not changed. I have checked the data topics of lidar and imu, and there is nothing wrong. The frequency of lidar is 10Hz, and the frequency of imu is 200Hz. What are the possible reasons for the above case? Looking forward to your reply~
![Screenshot from 2023-06-17 14-40-19](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/61641798/5d510e21-100e-4a03-9d0f-81409c7bc97a)
![Screenshot from 2023-06-17 14-40-34](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/61641798/ba0ac389-aa89-400b-af8b-1f51cc154ce0)
![Screenshot from 2023-06-17 14-44-04](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/61641798/9100873e-1cc6-48e9-b2a2-d565ae464e26)

**Comment by kennyjchen** [comment]
Yeah I haven't tested Livox support out since I don't have any data. Think you could upload a bag for me to play around with? Thanks!

**Comment by WeilongXia** [comment]
This is the dataset of Livox-mid360: https://1drv.ms/u/s!AjkIEg1kWUNeiAIZHIDBTzXmtHqf?e=cWek2u 
And the extrinsic between the Lidar frame and IMU frame is 
![Screenshot from 2023-06-17 13-39-45](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/61641798/d92f64e1-0afa-4280-938e-8e00213f8b0c)

**Comment by Joosoo1** [comment]
Yes, it seems that we are experiencing the same problem, may I ask if you are using it as a navigation for robots? Drones or unmanned vehicles?Maybe we can communicate that i have recently encountered some difficulties.

**Comment by WeilongXia** [comment]
Yeah I 'm going to use it as a localization module for drones, and maybe we can use the g-mail to communicate: xiawl0524@gmail.com

> Yes, it seems that we are experiencing the same problem, may I ask if you are using it as a navigation for robots? Drones or unmanned vehicles?Maybe we can communicate that i have recently encountered some difficulties.↳

**Comment by Joosoo1** [comment]
ok, after my test, livox-mid360 can run DLIO successfully, just change the point cloud publishing form "xfer_format" to "2" in livox_ros_driver2, then it can run DLIO successfully. DLIO can be run successfully, as follows:

![Effect Screenshot](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/65029285/b3a13f38-13e8-4f1e-85b2-013554af5b4f)
![xfer_format](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/65029285/222b2eeb-8cb3-440a-b83b-f1a0cfb60e09)

**Comment by Joosoo1** [comment]
But the results do not seem to be very good, odom data z-axis jitter will be relatively large, may be due to the reason of not tuning parameters, but also may be due to the built-in imu noise is too large, the follow-up we can exchange about how to make it better and more stable, in addition, I am also intended to apply it to the top of the drone, used as navigation and positioning.

**Comment by WeilongXia** [comment]
Thanks to your reply, the dimension of the acceleration data from the build-in imu in Livox MID-360 is g(gravity) instead of m/s^2, maybe you should multiply the data with a constant value like 9.8?

**Comment by Joosoo1** [comment]
> Thanks to your reply, the dimension of the acceleration data from the build-in imu in Livox MID-360 is g(gravity) instead of m/s^2, maybe you should multiply the data with a constant value like 9.8?

ok,i will try!If you have better results, please let me know too!

**Comment by Joosoo1** [comment]
wow! Your results look great, the position estimation is accurate and the built point cloud map has no drift, but my results are as bad as ever, still with a large offset on the z-axis, can you share your configuration parameters file? Also, about the z-axis, my livox has a z-axis  accel bias of -5, while yours is 0. I think there is something wrong here.
![Result 3](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/65029285/2a4a74a5-ad2e-4830-9254-5e266c49b3c2)
![Result 4](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/65029285/1e254f65-c5f4-4d80-b97d-3bb6877cbcbd)

**Comment by kennyjchen** [comment]
Hi @WeilongXia and @Joosoo1 -- thanks for the great discussion you two have started here. Looks like the Livox branch is working! It just needs to be published in the standard format.

Yeah something is definitely wrong if the IMU biases are that large. Have you checked your extrinsics? That's typically an issue, especially since the convention for IMU and LiDAR are different.

**Comment by kennyjchen** [comment]
@Joosoo1 Yes, change the units of the accelerometer to m/s^2 as per the advice above.

Could someone record me a dataset in the new xfer_format? Thanks.

**Comment by Joosoo1** [comment]
Well, it's true that because of the acceleration units, it has to be m/s^2 for it to work well.Later, I will provide you with the dataset.
`void dlio::OdomNode::getScanFromROS(const sensor_msgs::PointCloud2ConstPtr& pc) {

  pcl::PointCloud<PointType>::Ptr original_scan_ (boost::make_shared<pcl::PointCloud<PointType>>());
  pcl::fromROSMsg(*pc, *original_scan_);

  // Remove NaNs
  std::vector<int> idx;
  original_scan_->is_dense = false;
  pcl::removeNaNFromPointCloud(*original_scan_, *original_scan_, idx);

  // Crop Box Filter
  this->crop.setInputCloud(original_scan_);
  this->crop.filter(*original_scan_);

  // automatically detect sensor type
  this->sensor = dlio::SensorType::UNKNOWN;
  for (auto &field : pc->fields) {
    if (field.name == "t") {
      this->sensor = dlio::SensorType::OUSTER;
      break;
    } else if (field.name == "time") {
      this->sensor = dlio::SensorType::VELODYNE;
      break;
    } else if (field.name == "offset_time") {
      this->sensor = dlio::SensorType::LIVOX;
      break;
    } else if (field.name == "timestamp") {
      this->sensor = dlio::SensorType::HESAI;
      break;
    }
  }

  if (this->sensor == dlio::SensorType::UNKNOWN) {
    this->deskew_ = false;
  }

  this->scan_header_stamp = pc->header.stamp;
  this->original_scan = original_scan_;

}
`
This distortion correction does not seem to work！

**Comment by dxdydz3dt** [comment]
Can you translate in English Please!. I am trying to run Livox but its not working

**Comment by Joosoo1** [comment]
> Can you translate in English Please!. I am trying to run Livox but its not working
You can take a look at this: https://github.com/vectr-ucla/direct_lidar_inertial_odometry/issues/5#issuecomment-1600450012

It is necessary to additionally convert the acceleration units of the /livox/imu topic output to m/s^2,then the DLIO will work well, of course all this needs to be under the source code of the livox branch.

**Comment by kennyjchen** [comment]
Hmm, yeah unfortunately it looks like in the `livox_ros_driver2` package, only `x` `y` `z` and `intensity` fields are copied over when publishing using the `xfer_format: 2` value. 

https://github.com/Livox-SDK/livox_ros_driver2/blob/master/src/lddc.cpp#L437

It looks like with their custom message, they have [per-point timestamps ](https://github.com/Livox-SDK/livox_ros_driver2/blob/master/src/lddc.cpp#L292). However, it looks like both [`timestamp`](https://github.com/Livox-SDK/livox_ros_driver2/blob/master/src/lddc.cpp#L292) and [`offset_time`](https://github.com/Livox-SDK/livox_ros_driver2/blob/master/src/lddc.cpp#L292) are used, which is a bit confusing since [their CustomPoint.msg contains `offset_time`](https://github.com/Livox-SDK/livox_ros_driver2/blob/master/msg/CustomPoint.msg), but the data above (the first link) has a `timestamp` field.

If only timestamps are available using their custom point format, we'll need to build support for that (unless they add timestamps to the PCL format). I'll keep digging.

**Comment by kennyjchen** [comment]
Ok -- I think I might have figured this out. For future reference, this is how different sensors timestamp their points:
- Ouster: field `t` of type `std::uint32_t`, which is the time relative to the beginning of the scan in nanoseconds
- Velodyne: field `time` of type `float`, which is the time relative to the beginning of the scan in seconds
- Livox: field `timestamp` of type `double`, which is the absolute time of the point since epoch in nanoseconds
- Hesai: field `timestamp` of type `double`, which is the absolute time of the point since epoch in seconds

I pushed a few changes to the `feature/livox-support` branch. Please test this out using the original `xfer_format` value so that there are timestamp fields.

@WeilongXia -- I played around with your data, and it looks like the LiDAR and IMU measurements are not time synchronized. Is there an option in the Livox driver to synchronize them somehow?

**Comment by WeilongXia** [comment]
Ok, I found a timesync choice in the config file like this
![Screenshot from 2023-06-24 11-27-10](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/61641798/86e38183-5aa1-4c74-add4-09a4b36bc044)
and I'll try to record a new rosbag.

**Comment by juliangaal** [comment]
@WeilongXia could you rename the issue to something more meaningful, if you don't mind, for future reference? Something like "No localization with Livox Lidar"

**Comment by WeilongXia** [comment]
> 

I tested the 'feature/livox-support' branch with the original xfer_format, but there is no localization output.

**Comment by yijing2050** [comment]
> ld multiply the data with a constant value like 9.8?

@Joosoo1 I used xfer_format  = 0,and there was no point cloud. My wechat:yijingxs, you can add me and it is convenient to communicate with each other

**Comment by Joosoo1** [comment]
> 
Yes, I tested the new branch and the DLIO only has odom output when xfer_format=2, but the result is completely wrong, so I have been using the original DLIO now, the original DLIO works well, I tested it on the drone and the positioning is very good. But deskwing is not working and will have some effect on DLIO，So I look forward to the author's help in solving this problem.

**Comment by Joosoo1** [comment]
> > ld multiply the data with a constant value like 9.8?
> 
> @Joosoo1 I used xfer_format = 0,and there was no point cloud. My wechat:yijingxs, you can add me and it is convenient to communicate with each other
xfer_format = 2, old DLIO could working!

**Comment by Joosoo1** [comment]
> > > ld multiply the data with a constant value like 9.8?
> > 
> > 
> > @Joosoo1 I used xfer_format = 0,and there was no point cloud. My wechat:yijingxs, you can add me and it is convenient to communicate with each other
> > xfer_format = 2, old DLIO could working!

Also, when you use imu with acceleration units of m/s^2, you should change the https://github.com/vectr-ucla/direct_lidar_inertial_odometry/tree/feature/livox-support/src/ under the livox branch Lines 1373 to 1375 of the code in dlio/odom.cc should be changed to `Eigen::Vector3f lin_accel(imu_raw->linear_acceleration.x * gravity_, imu_raw->linear_acceleration.y * gravity_, imu_raw->linear_acceleration.z * gravity_);` recompile！

**Comment by yijing2050** [comment]
Thanks for your reply and kind advice. I have another problem when compiling, the first is the version of cmake. As my ros version is melodic,and the cmake version is 3.10.2, so I modify 

#VERSION 3.12.4
cmake_minimum_required(VERSION 3.10.2)
project(direct_lidar_inertial_odometry)
Could this modification do influence the output of the code?

&nbsp;it have no add_compile_definitions.Then I comment out the section:# Not all machines have <cpuid.h&gt; available
#set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
#file(WRITE ${CMAKE_BINARY_DIR}/test_cpuid.cpp "#include <cpuid.h&gt;")
#try_compile(HAS_CPUID ${CMAKE_BINARY_DIR} ${CMAKE_BINARY_DIR}/test_cpuid.cpp)
#file(REMOVE ${CMAKE_BINARY_DIR}/test_cpuid.cpp)
#if(HAS_CPUID)
#&nbsp; add_compile_definitions(HAS_CPUID)
#endif()
after done above, I compiled successfully.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月26日(星期一) 中午11:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vectr-ucla/direct_lidar_inertial_odometry] No localization with Livox Lidar (Issue #5)





    
ld multiply the data with a constant value like 9.8?
  
@Joosoo1 I used xfer_format = 0,and there was no point cloud. My wechat:yijingxs, you can add me and it is convenient to communicate with each other
 xfer_format = 2, old DLIO could working!
   
Also, when you use imu with acceleration units of m/s^2, you should change the https://github.com/vectr-ucla/direct_lidar_inertial_odometry/tree/feature/livox-support/src/ under the livox branch Lines 1373 to 1375 of the code in dlio/odom.cc should be changed to Eigen::Vector3f lin_accel(imu_raw-&gt;linear_acceleration.x * gravity_, imu_raw-&gt;linear_acceleration.y * gravity_, imu_raw-&gt;linear_acceleration.z * gravity_); recompile！

**Comment by Joosoo1** [comment]
> 

I do not know much about this problem, but it should not affect if the compilation is successful, you can actually test it!

**Comment by Joosoo1** [comment]
我对这个问题不太了解，不过编译成功的话应该不会影响，可以实际测试一下！

> Thanks for your reply and kind advice. I have another problem when compiling, the first is the version of cmake. As my ros version is melodic,and the cmake version is 3.10.2, so I modify #VERSION 3.12.4 cmake_minimum_required(VERSION 3.10.2) project(direct_lidar_inertial_odometry) Could this modification do influence the output of the code? &nbsp;it have no add_compile_definitions.Then I comment out the section:# Not all machines have <cpuid.h&gt; available #set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY) #file(WRITE ${CMAKE_BINARY_DIR}/test_cpuid.cpp "#include <cpuid.h&gt;") #try_compile(HAS_CPUID ${CMAKE_BINARY_DIR} ${CMAKE_BINARY_DIR}/test_cpuid.cpp) #file(REMOVE ${CMAKE_BINARY_DIR}/test_cpuid.cpp) #if(HAS_CPUID) #&nbsp; add_compile_definitions(HAS_CPUID) #endif() after done above, I compiled successfully.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年6月26日(星期一) 中午11:54 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [vectr-ucla/direct_lidar_inertial_odometry] No localization with Livox Lidar (Issue #5) ld multiply the data with a constant value like 9.8? @Joosoo1 I used xfer_format = 0,and there was no point cloud. My wechat:yijingxs, you can add me and it is convenient to communicate with each other xfer_format = 2, old DLIO could working! Also, when you use imu with acceleration units of m/s^2, you should change the https://github.com/vectr-ucla/direct_lidar_inertial_odometry/tree/feature/livox-support/src/ under the livox branch Lines 1373 to 1375 of the code in dlio/odom.cc should be changed to Eigen::Vector3f lin_accel(imu_raw-&gt;linear_acceleration.x * gravity_, imu_raw-&gt;linear_acceleration.y * gravity_, imu_raw-&gt;linear_acceleration.z * gravity_); recompile！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

I don't know much about this, but if it compiles successfully, you should be able to run the program successfully, so you can test it as soon as possible!

**Comment by kennyjchen** [comment]
@yijing2050 Unfortunately DLIO only supports ROS Noetic, but it sounds like you got it working. Removing those lines won't have any affect on the output; it's just to build support for [ARM architectures](https://github.com/vectr-ucla/direct_lidar_odometry/issues/16).

@WeilongXia @Joosoo1 The `xfer_format` should be `0` so that it's a message of type PointCloud2 but contains the timestamps. I will look into this again later this week. Sorry to ask again -- could someone record me a new bag that ideally time synchronizes the Mid-360's LiDAR and IMU (if not already), using `xfer_format: 0`? Thank you. In the meanwhile, you can turn deskewing off, but note that (especially at 10Hz) the point clouds will be quite distorted.

**Comment by yijing2050** [comment]
@kennyjchen 
[Uploading livox_repub.zip…]()

**Comment by yijing2050** [comment]
Actually, I have compiled successfully although, but i haven't got the odom.. The configuration is as the below.
![2023-06-27 10-12-35屏幕截图](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/37020759/dcd3682a-9fe1-4207-a68c-b39873099cfd)
![2023-06-27 10-12-02屏幕截图](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/37020759/af2a4edb-8ce7-4939-92b8-7e3501324763)
![2023-06-27 10-12-59屏幕截图](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/37020759/5feb8edc-422e-45fe-8ea1-b6695fdae5e1)
![2023-06-27 10-22-02屏幕截图](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/37020759/1d646cbb-0a74-4dae-aff3-5fe31709459a)
![2023-06-27 10-21-39屏幕截图](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/37020759/a17c2cc2-4c74-4cc9-b6df-1512aebd2b56)
![2023-06-27 10-21-14屏幕截图](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/37020759/20d5c171-4d12-4340-913f-e09a0f160943)

**Comment by kennyjchen** [comment]
Ok -- after digging through the Livox driver and also looking at [this dataset](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/issues/5#issuecomment-1598064297), it seems like there is a bug for per-point timestamps when using `xfer_format: 0`(i.e., `Livox pointcloud2(PointXYZRTLT) pointcloud format`). The point cloud and IMU timestamps look synchronized, but the point timestamps are off and do not fall within the sweep window for some reason.

I looked at other Mid-360 packages, and it seems like most people use `xfer_format: 2` so that the `offset_time` field contains the time since the beginning of the sweep.

So new plan: please try the [updated branch](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/commit/6b152351357708dd5e5db2ccb0c53c65aad656ad) but with `xfer_format: 2`. Your topic of type `livox_ros_driver::CustomMsg` should be called `/robot/livox`, which will call [this new callback](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/blob/feature/livox-support/src/dlio/odom.cc#L1000-L1023). This is all assuming that [`offset_time`](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/blob/feature/livox-support/src/dlio/odom.cc#L1000-L1023) is in nanoseconds relative to the beginning of the sweep (which I think is the case).

(Please be careful with the units of gravity. I [removed](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/commit/6b152351357708dd5e5db2ccb0c53c65aad656ad#diff-2ed26eca15f057967bfc05c426ba09f51e70c50d65116f355b109b2f84269acbL854-L856) the previous multiplication with gravity.)

Note that I have not tested this at all, because I do not have a Livox sensor or any bags with `xfer_format: 2`. If someone could record me one that would be great so I can test it on my side. Otherwise, let me know if it works or not!

**Comment by Joosoo1** [comment]
Sorry for the late reply, and thank you  @kennyjchen author for your efforts to solve this problem. Here is the dataset I recorded: accel in units when g
https://onedrive.live.com/?cid=6FAEBC9C8F25AA2C&id=6FAEBC9C8F25AA2C%21120&parId=root&o=OneUp

**Comment by kennyjchen** [comment]
Ok, I think I got it working. Credit to [this Tweet](https://twitter.com/devemin/status/1631461802084302850?lang=en) for supplying the data I played around with.

![image](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/7662578/a2dbca73-8acf-4179-8de6-144488e49458)

Please use the newer [`livox_ros_driver2` package](https://github.com/Livox-SDK/livox_ros_driver2) with `xfer_format: 1`. The latest `feature/livox-support` branch seems to be working with deskewing. Let me know.

**Comment by Joosoo1** [comment]
> Ok, I think I got it working. Credit to [this Tweet](https://twitter.com/devemin/status/1631461802084302850?lang=en) for supplying the data I played around with.
> 
> ![image](https://user-images.githubusercontent.com/7662578/249576793-a2dbca73-8acf-4179-8de6-144488e49458.png)
> 
> **Please use the newer [`livox_ros_driver2` package](https://github.com/Livox-SDK/livox_ros_driver2) with `xfer_format: 1`.** The latest `feature/livox-support` branch seems to be working with deskewing. Let me know.

Doesn't seem to work：
![new-DLIO](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/65029285/e7d24d6a-a8c9-43cf-b896-54c8cc93eb45)

**Comment by WeilongXia** [comment]
> > Ok, I think I got it working. Credit to [this Tweet](https://twitter.com/devemin/status/1631461802084302850?lang=en) for supplying the data I played around with.↳
> > ![image](https://user-images.githubusercontent.com/7662578/249576793-a2dbca73-8acf-4179-8de6-144488e49458.png)
> > **Please use the newer [`livox_ros_driver2` package](https://github.com/Livox-SDK/livox_ros_driver2) with `xfer_format: 1`.** The latest `feature/livox-support` branch seems to be working with deskewing. Let me know.↳
> 
> Doesn't seem to work： ![new-DLIO](https://user-images.githubusercontent.com/65029285/250365750-e7d24d6a-a8c9-43cf-b896-54c8cc93eb45.png)↳

You should modify `livox_topic` to `"/livox/lidar"`, and `pointcloud_topic` to another one.
Hi author @kennyjchen , with `deskew` set to `"false"`, it can work with Livox-MID360 now as below!
![Screenshot from 2023-07-03 10-27-17](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/61641798/669a278d-dd3d-4b9a-b12f-7a77151d82a8)
 And the offset_time units in livox_ros_driver2 is microseconds.

**Comment by WeilongXia** [comment]
Hi author, when i set `deskew` to `true`, the program is not working properly, this is the dataset i used: https://1drv.ms/u/s!AjkIEg1kWUNeiArwedvaRRYd5hWB?e=BaII3v
Could you please help to figure this out?

**Comment by Joosoo1** [comment]
yes! DLIO is now working  with deskewing！just `livox_topic` to "/livox/lidar"

**Comment by kennyjchen** [comment]
Good to hear!

**Comment by yijing2050** [comment]
DLIO is now working with deskewing in Ubuntu 18.04, but it seems not stable and the path is not smooth as fast_lio2. And the map will fly in some time later.
![2023-07-06 22-21-28屏幕截图](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/37020759/79287d42-5c26-41d9-bec3-39ba884fac84)

**Comment by juliangaal** [comment]
@Joosoo1 what are the extrinsics of the dataset you provided?

**Comment by Joosoo1** [comment]
> @Joosoo1 what are the extrinsics of the dataset you provided?
Please use this dataset, I tested it and it works great!：https://1drv.ms/u/s!AjkIEg1kWUNeiArwedvaRRYd5hWB?e=BaII3v
The extrinsics are as follows：
![image](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/65029285/ec769812-5991-40df-9d9a-93bb19877555)

**Comment by CharlieV5** [comment]
May I ask you guys what is the meaning of dlio/pointcloud/dekew in dlio.yaml? Does it mean that this program will do the deskewing for pointcloud, or this program will consider the input points has been deskewed so it will no do the deskewing? What will happen when dlio/pointcloud/dekew is set as false? Thank you!

> > > Ok, I think I got it working. Credit to [this Tweet](https://twitter.com/devemin/status/1631461802084302850?lang=en) for supplying the data I played around with.↳
> > > ![image](https://user-images.githubusercontent.com/7662578/249576793-a2dbca73-8acf-4179-8de6-144488e49458.png)
> > > **Please use the newer [`livox_ros_driver2` package](https://github.com/Livox-SDK/livox_ros_driver2) with `xfer_format: 1`.** The latest `feature/livox-support` branch seems to be working with deskewing. Let me know.↳
> > 
> > 
> > Doesn't seem to work： ![new-DLIO](https://user-images.githubusercontent.com/65029285/250365750-e7d24d6a-a8c9-43cf-b896-54c8cc93eb45.png)↳
> 
> You should modify `livox_topic` to `"/livox/lidar"`, and `pointcloud_topic` to another one. Hi author @kennyjchen , with `deskew` set to `"false"`, it can work with Livox-MID360 now as below! ![Screenshot from 2023-07-03 10-27-17](https://user-images.githubusercontent.com/61641798/250429625-669a278d-dd3d-4b9a-b12f-7a77151d82a8.png) And the offset_time units in livox_ros_driver2 is microseconds.

**Comment by kennyjchen** [comment]
It will undistort the point cloud when set to true.

**Comment by CharlieV5** [comment]
> It will undistort the point cloud when set to true.

Thanks

**Comment by 85256638** [comment]
> > > @Joosoo1 what are the extrinsics of the dataset you provided?
> > > Please use this dataset, I tested it and it works great!：https://1drv.ms/u/s!AjkIEg1kWUNeiArwedvaRRYd5hWB?e=BaII3v
> > > The extrinsics are as follows：
> > > ![image](https://private-user-images.githubusercontent.com/65029285/252843712-ec769812-5991-40df-9d9a-93bb19877555.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDYwODgsIm5iZiI6MTcyNjE0NTc4OCwicGF0aCI6Ii82NTAyOTI4NS8yNTI4NDM3MTItZWM3Njk4MTItNTk5MS00MGRmLTlkOWEtOTNiYjE5ODc3NTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDEyNTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NDgzZGJjNDkxNTU0MTliMmRiMDJlOGYyNWZlYTU3MGFkNGIzYzIwNTE1MDBlNjQyMDU4ZWVkY2FlMzE0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QeoMoWEww-brlixtBHsRrXNcP5rUnOUNKV_IaBvoss)
> 
> Hi, can you kindly let me know where to update those extrinsic values? I guess in the `dlio.yaml`? can you kindly paste yours please? I would like to know how to adapt Livox Horizon's extrinsic from the datasheet to the dlio.yaml configuration.
> 
> ```
> dlio:
> 
>   version: 1.1.1
> 
>   adaptive: true
> 
>   pointcloud:
>     deskew: true
>     voxelize: true
> 
>   imu:
>     calibration: true
>     intrinsics:
>       accel:
>         bias: [ 0.0, 0.0, 0.0 ]
>         sm:   [ 1.,  0.,  0.,
>                 0.,  1.,  0.,
>                 0.,  0.,  1. ]
>       gyro:
>         bias: [ 0.0, 0.0, 0.0 ]
> 
>   extrinsics:
>     baselink2imu:
>       t: [ 0.006253, -0.011775, 0.007645 ]
>       R: [ 1.,  0.,  0.,
>            0.,  1.,  0.,
>            0.,  0.,  1. ]
>     baselink2lidar:
>       t: [ 0.,  0.,  0. ]
>       R: [ 1.,  0.,  0.,
>            0.,  1.,  0.,
>            0.,  0.,  1. ]
> ```
> 
> LIvox Horizon extrinsic: ![image](https://private-user-images.githubusercontent.com/3270742/367205751-f3791ad1-8704-4bac-ac88-5a44abfaf8de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDk1OTYsIm5iZiI6MTcyNjQwOTI5NiwicGF0aCI6Ii8zMjcwNzQyLzM2NzIwNTc1MS1mMzc5MWFkMS04NzA0LTRiYWMtYWM4OC01YTQ0YWJmYWY4ZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMTQwODE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzNlOWE2NWVjMzFiNzFhODA1NWRiZTk4ZDI5MWI5NDFiNDYxNjdjNmUyOWEyYTMxNjBkN2JiMTQ2ZDU4NTAyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B1knzeKU-nONNHOmjkxD4zZFlX9qwuRDuD_Asq5zi1A)

@kennyjchen @Joosoo1 this issue has been closed, I would love to hear your advice :) thanks!

**Comment by thisisdipanjan** [comment]
> May I ask you guys what is the meaning of dlio/pointcloud/dekew in dlio.yaml? Does it mean that this program will do the deskewing for pointcloud, or this program will consider the input points has been deskewed so it will no do the deskewing? What will happen when dlio/pointcloud/dekew is set as false? Thank you!
> 
> > > > Ok, I think I got it working. Credit to [this Tweet](https://twitter.com/devemin/status/1631461802084302850?lang=en) for supplying the data I played around with.↳
> > > > ![image](https://user-images.githubusercontent.com/7662578/249576793-a2dbca73-8acf-4179-8de6-144488e49458.png)
> > > > **Please use the newer [`livox_ros_driver2` package](https://github.com/Livox-SDK/livox_ros_driver2) with `xfer_format: 1`.** The latest `feature/livox-support` branch seems to be working with deskewing. Let me know.↳
> > > 
> > > 
> > > Doesn't seem to work： ![new-DLIO](https://user-images.githubusercontent.com/65029285/250365750-e7d24d6a-a8c9-43cf-b896-54c8cc93eb45.png)↳
> > 
> > 
> > You should modify `livox_topic` to `"/livox/lidar"`, and `pointcloud_topic` to another one. Hi author [@kennyjchen](https://github.com/kennyjchen) , with `deskew` set to `"false"`, it can work with Livox-MID360 now as below! ![Screenshot from 2023-07-03 10-27-17](https://user-images.githubusercontent.com/61641798/250429625-669a278d-dd3d-4b9a-b12f-7a77151d82a8.png) And the offset_time units in livox_ros_driver2 is microseconds.

The pointcloud topic has to be livox/lidar right so whats the livox topic is about? can it stay livox/lidar ?
